<a href="https://colab.research.google.com/github/alishadaudi/ddsa-data-science-project-sql/blob/main/SQL_April_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Code snippet 1
# Importing the dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/Tarrant%20County%20Income%20Dataset%20SQL%20CSV.csv')

# Display the data
data

,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,39,State-gov,77516,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 2
# Importing sqlite3 (to run SQL queries in Python)
import sqlite3

In [ ]:
# Code snippet 3
# Creating a sample (dummy) database as a connection
conn = sqlite3.connect('sample.db')

In [ ]:
# Code snippet 4
# Storing the pandas dataframe as a table in the sample database
data.to_sql('data_sql', conn)

32561

In [ ]:
# Code snippet 5
# Selecting ALL the data from the data_sql table
sql_query = ''' SELECT * FROM data_sql '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,0,39,State-gov,77516,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,1,50,Self-emp-not-inc,83311,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,2,38,Private,215646,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,4,28,Private,338409,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,32556,27,Private,257302,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,32557,40,Private,154374,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 6
# Selecting ALL the customer data from the data_sql table whose age is more than 50
sql_query = ''' SELECT * FROM data_sql WHERE age > 50 '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
1,7,52,Self-emp-not-inc,209642,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
2,21,54,Private,302146,HS-grad,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
3,24,59,Private,109015,HS-grad,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
4,25,56,Local-gov,216851,Bachelors,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6455,32542,72,None,129912,HS-grad,Married-civ-spouse,None,Husband,White,Male,0,0,25,United-States,<=50K
6456,32548,65,Self-emp-not-inc,99359,Prof-school,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
6457,32554,53,Private,321865,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
6458,32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
6459,32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 7
# Selecting ALL the customer data from the data_sql table whose age is <= 50
sql_query = ''' SELECT * FROM data_sql WHERE age <= 50 '''
data_output = pd.read_sql(sql_query, conn)
data_output

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,0,39,State-gov,77516,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,1,50,Self-emp-not-inc,83311,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,2,38,Private,215646,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,4,28,Private,338409,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,5,37,Private,284582,Masters,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26096,32553,32,Private,116138,Masters,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
26097,32555,22,Private,310152,Some-college,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
26098,32556,27,Private,257302,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
26099,32557,40,Private,154374,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
26100,32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [ ]:
# Code snippet 8
# Selecting age, work class, education, marital status, income from the data_sql table
sql_query = ''' SELECT age, Workclass, Education, Marital_Status, Income FROM data_sql '''
data_output = pd.read_sql(sql_query, conn)
data_output

       Age         Workclass   Education      Marital_Status Income
0       39         State-gov   Bachelors       Never-married  <=50K
1       50  Self-emp-not-inc   Bachelors  Married-civ-spouse  <=50K
2       38           Private     HS-grad            Divorced  <=50K
3       53           Private        11th  Married-civ-spouse  <=50K
4       28           Private   Bachelors  Married-civ-spouse  <=50K
...    ...               ...         ...                 ...    ...
32556   27           Private  Assoc-acdm  Married-civ-spouse  <=50K
32557   40           Private     HS-grad  Married-civ-spouse   >50K
32558   58           Private     HS-grad             Widowed  <=50K
32559   22           Private     HS-grad       Never-married  <=50K
32560   52      Self-emp-inc     HS-grad  Married-civ-spouse   >50K

[32561 rows x 5 columns]

In [ ]:
# Code snippet 9
# Selecting age, marital status from the data_sql table whose age < 30 and marital status is Never-married
sql_query = ''' SELECT age, Marital_Status FROM data_sql WHERE age < 30 AND marital_status = 'Never-married'  '''
data_output = pd.read_sql(sql_query, conn)
data_output

      Age Marital_Status
0      23  Never-married
1      25  Never-married
2      19  Never-married
3      23  Never-married
4      20  Never-married
...   ...            ...
7161   26  Never-married
7162   22  Never-married
7163   22  Never-married
7164   22  Never-married
7165   22  Never-married

[7166 rows x 2 columns]

In [ ]:
# Code snippet 10
# Selecting age, marital status from the data_sql table whose age > 40 and marital status is Married-civ-spouse
sql_query = ''' SELECT age, Marital_Status FROM data_sql WHERE age > 40 AND marital_status = 'Married-civ-spouse'  '''
data_output = pd.read_sql(sql_query, conn)
data_output

      Age      Marital_Status
0      50  Married-civ-spouse
1      53  Married-civ-spouse
2      52  Married-civ-spouse
3      42  Married-civ-spouse
4      43  Married-civ-spouse
...   ...                 ...
8185   43  Married-civ-spouse
8186   43  Married-civ-spouse
8187   43  Married-civ-spouse
8188   53  Married-civ-spouse
8189   52  Married-civ-spouse

[8190 rows x 2 columns]

In [ ]:
# Code snippet 11
# Selecting different/unique marital_statuses in the dataset
sql_query = ''' SELECT DISTINCT Marital_Status FROM data_sql '''
data_output = pd.read_sql(sql_query, conn)
data_output

          Marital_Status
0          Never-married
1     Married-civ-spouse
2               Divorced
3  Married-spouse-absent
4              Separated
5      Married-AF-spouse
6                Widowed

In [ ]:
# Code snippet 12
# Selecting different/unique marital_statuses and their RESPECTIVE counts in the dataset
sql_query = ''' SELECT Marital_Status, count(Marital_Status) FROM data_sql GROUP BY Marital_Status'''
data_output = pd.read_sql(sql_query, conn)
data_output

          Marital_Status  count(Marital_Status)
0               Divorced                   4443
1      Married-AF-spouse                     23
2     Married-civ-spouse                  14976
3  Married-spouse-absent                    418
4          Never-married                  10683
5              Separated                   1025
6                Widowed                    993

In [ ]:
# Code snippet 12.1
# Selecting different/unique marital_statuses and their RESPECTIVE counts in the dataset - order by the count descending
sql_query = ''' SELECT Marital_Status, count(Marital_Status) FROM data_sql GROUP BY Marital_Status ORDER BY count(Marital_Status) DESC '''
data_output = pd.read_sql(sql_query, conn)
data_output

          Marital_Status  count(Marital_Status)
0     Married-civ-spouse                  14976
1          Never-married                  10683
2               Divorced                   4443
3              Separated                   1025
4                Widowed                    993
5  Married-spouse-absent                    418
6      Married-AF-spouse                     23

In [ ]:
# Code snippet 13
# Selecting different/unique education and their RESPECTIVE counts in the dataset - order by the count descending
sql_query = ''' SELECT education, count(education) FROM data_sql GROUP BY education ORDER BY count(education) DESC '''
data_output = pd.read_sql(sql_query, conn)
data_output

       Education  count(education)
0        HS-grad             10501
1   Some-college              7291
2      Bachelors              5355
3        Masters              1723
4      Assoc-voc              1382
5           11th              1175
6     Assoc-acdm              1067
7           10th               933
8        7th-8th               646
9    Prof-school               576
10           9th               514
11          12th               433
12     Doctorate               413
13       5th-6th               333
14       1st-4th               168
15     Preschool                51

In [ ]:
# Code snippet 14
# Selecting different/unique education, their RESPECTIVE counts and their average capital gains in the dataset - order by the count descending
sql_query = ''' SELECT education, count(education), avg(Capital_Gain) FROM data_sql GROUP BY education ORDER BY avg(Capital_Gain) DESC '''
data_output = pd.read_sql(sql_query, conn)
data_output

       Education  count(education)  avg(Capital_Gain)
0    Prof-school               576       10414.416667
1      Doctorate               413        4770.145278
2        Masters              1723        2562.563552
3      Bachelors              5355        1756.299533
4      Preschool                51         898.392157
5      Assoc-voc              1382         715.051375
6     Assoc-acdm              1067         640.399250
7   Some-college              7291         598.824167
8        HS-grad             10501         576.800114
9           10th               933         404.574491
10           9th               514         342.089494
11          12th               433         284.087760
12       7th-8th               646         233.939628
13          11th              1175         215.097872
14       5th-6th               333         176.021021
15       1st-4th               168         125.875000

In [ ]:
# Code snippet 15
# Selecting different/unique education, their RESPECTIVE counts and their average capital gains in the dataset WITH atleast 1000 instances /records- order by the count descending
sql_query = ''' SELECT education, count(education), avg(Capital_Gain) FROM data_sql GROUP BY education HAVING count(education) > 1000 ORDER BY avg(Capital_Gain) DESC '''
data_output = pd.read_sql(sql_query, conn)
data_output

      Education  count(education)  avg(Capital_Gain)
0       Masters              1723        2562.563552
1     Bachelors              5355        1756.299533
2     Assoc-voc              1382         715.051375
3    Assoc-acdm              1067         640.399250
4  Some-college              7291         598.824167
5       HS-grad             10501         576.800114
6          11th              1175         215.097872

In [ ]:
# Code snippet 16
# Selecting different/unique education, their RESPECTIVE counts and their average number of hours order by the count descending
sql_query = ''' SELECT education, count(education), avg(Hours_per_Week) FROM data_sql GROUP BY education ORDER BY avg(Hours_per_Week) DESC '''
data_output = pd.read_sql(sql_query, conn)
data_output

       Education  count(education)  avg(Hours_per_Week)
0    Prof-school               576            47.425347
1      Doctorate               413            46.973366
2        Masters              1723            43.836332
3      Bachelors              5355            42.614006
4      Assoc-voc              1382            41.610709
5        HS-grad             10501            40.575374
6     Assoc-acdm              1067            40.504217
7        7th-8th               646            39.366873
8        5th-6th               333            38.897898
9   Some-college              7291            38.852284
10       1st-4th               168            38.255952
11           9th               514            38.044747
12          10th               933            37.052519
13     Preschool                51            36.647059
14          12th               433            35.780600
15          11th              1175            33.925957